config/routes.rb
Rails.application.routes.draw do

  root 'static#home', as: 'home'

  ##Session
  get '/client_login', to: 'sessions#client_login', as: 'client_login'
  post '/client_login', to: 'sessions#login_client'
  get '/coach_login', to: 'sessions#coach_login', as: 'coach_login'
  post '/coach_login', to: 'sessions#login_coach'
  delete '/', to: 'sessions#logout', as: 'logout'

  ##Expertise
  post '/expertises', to: 'expertises#create', as: 'new_expertise'
  delete '/expertises/:id', to: 'expertises#destroy', as: 'delete_expertise'

  ##WorkoutExercise
  post '/workout_exercises', to: 'workout_exercises#create', as: 'new_workout_exercise'
  delete '/workout_exercises/:id', to: 'workout_exercises#destroy', as: 'delete_workout_exercise'

  ##Workouts
  get '/workouts', to: 'workouts#index', as: 'workouts'
  get '/workouts/new', to: 'workouts#new', as: 'new_workout'
  post '/workouts', to: 'workouts#create'
  patch '/workouts/:id/completed', to: 'workouts#completed', as: 'completed_workout' 
  get '/workouts/:id', to: 'workouts#show', as: 'workout'
  delete '/workouts/:id', to: 'workouts#destroy', as: 'delete_workout'

  ##Exercise
  get '/exercises', to: 'exercises#index', as: 'exercises'
  get '/exercises/new', to: 'exercises#new', as: 'new_exercise'
  post '/exercises', to: 'exercises#create'
  get '/exercises/:id/edit', to: 'exercises#edit', as: 'edit_exercise'
  patch '/exercises/:id', to: 'exercises#update'
  get '/exercises/:id', to: 'exercises#show', as: 'exercise'

  ##Category
  get '/categories/:id/edit', to: 'categories#edit', as: 'edit_category'
  patch '/categories/:id', to: 'categories#update'
  get '/categories', to: 'categories#index', as: 'categories'
  get '/categories/:id', to: 'categories#show', as:'category'

  ##Coaches
  get '/coaches', to: 'coaches#index', as: 'coaches'
  get '/coaches/new', to: 'coaches#new', as: 'new_coach'
  post '/coaches', to: 'coaches#create'
  get '/coaches/:id/edit', to: 'coaches#edit', as: 'edit_coach'
  patch '/coaches/:id', to: 'coaches#update'
  get '/coaches/:id', to: 'coaches#show', as: 'coach'

  ##Clients
  get '/clients', to: 'clients#index', as: 'clients'
  get '/clients/new', to: 'clients#new', as: 'new_client'
  post '/clients', to: 'clients#create'
  get '/clients/:id/edit', to: 'clients#edit', as: 'edit_client'
  patch '/clients/:id', to: 'clients#update'
  get '/clients/:id', to: 'clients#show', as: 'client'
  
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :client

  has_many :workout_exercises
  has_many :exercises, through: :workout_exercises

  validates :name, presence: true
  validates :length, numericality: { greater_than: 0 }
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :completed, :destroy]
  
  def show
  end

  def index
    @workouts = Workout.all
  end

  def new
    unless logged_in_as_coach?
      flash[ :messages ] = [ "You must be logged in as a coach to create a new workout!" ]
      redirect_to client_path( session[ :id ] )
    end
    @new_workout = Workout.new
  end

  def create
    new_workout = Workout.create( workout_params )
    if new_workout.valid?
      redirect_to workout_path( new_workout )
    else
      flash[ :messages ] = new_workout.errors.full_messages
      redirect_to new_workout_path
    end
  end

  def edit
  end

  def update
  end

  def completed
    @workout.update( completed: @workout.completed ? false : true )
    redirect_to workout_path( @workout )
  end

  def destroy
    @workout.workout_exercises.each(&:destroy)
    @workout.destroy
    redirect_to client_path(@workout.client)
  end

  private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require( :workout ).permit( :client_id, :name, :length )
  end

end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/index.html.erb
<h1>Workouts#index</h1>
<p>Find me in app/views/workouts/index.html.erb</p>

app/views/workouts/new.html.erb
<h1>
    <%= image_tag "WorkoutIcon.svg", class: "model-icon" %>
    Create a new workout
</h1>

<% if flash[ :messages ] %>
    <ul>
    <% flash[ :messages ].each do | error_message | %>
        <li style="color:red;"><%= error_message %></li>
    <% end %>
    </ul>
<% end %>

<div class="imput-group">
    <%= form_for @new_workout do | f | %>
     <div class="input-group-prepend">
        <%= f.label :client_id, class: 'input-group-text'%>
        <%= f.collection_select :client_id, Client.where( coach_id: session[ :id ] ), :id, :name, class: 'form-control' %>
    </div>
    <div class="input-group-prepend">
        <%= f.label :name, "New workout name:", class: 'input-group-text' %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="input-group-prepend">
        <%= f.label :length, "Length (in mins.):", class: 'input-group-text' %>
        <%= f.number_field :length, class: 'form-control' %>
    </div>
    <%= f.submit "Create Workout", class: 'btn-primary'%>
    <% end %>
</div>

app/views/workouts/show.html.erb
<h1>
    <%= image_tag "WorkoutIcon.svg", class: "model-icon" %>
    Workout: <%= @workout.name %>
</h1>


<div class="cards">
    <div class="card">
        <%= image_tag @workout.client.avatar, class: "card-img-top" %>
        <div class="card-body">
            <h2 class="card-title">Client: <%= @workout.client.name %></h2>
            <p class="card-text"><%= @workout.client.bio %></p>
            <%= button_to "View Profile", client_path(@workout.client), method: "get", class: "btn-primary" %>
        </div>
    </div>
    <div class="card">
        <%= image_tag @workout.client.coach.avatar, class: "card-img-top" %>
        <div class="card-body">
            <h2 class="card-title">Coach: <%= @workout.client.coach.name %></h2>
            <p class="card-text"><%= @workout.client.coach.bio %></p>
            <%= button_to "View Profile", coach_path(@workout.client.coach), method: "get", class: "btn-primary" %>
        </div>
    </div>
</div>

<h3><%= @workout.completed ? "This workout was completed on #{ @workout.updated_at.strftime("%F") }" : "This workout has not been completed yet" %></h3>
<% if (logged_in_as_client? && current_user.id == @workout.client.id) || (logged_in_as_coach? && current_user.id == @workout.client.coach.id) %>
    <%= button_to @workout.completed ? "Mark as not completed" : "Mark as completed", completed_workout_path( @workout ), method: "patch", class: "btn-primary" %>
<% end %>
<hr />


<% if logged_in_as_coach? && current_user.id == @workout.client.coach.id %>
    <div class="input-group">
    <%= form_with scope: :workout_exercise, url: new_workout_exercise_path(params: {workout_id: @workout.id}), method: 'post' do |f|%>
        <div class="input-group-prepend">
            <%= f.label "Add an exercise to this workout", class: 'input-group-text' %>
            <%= f.collection_select :exercise_id, Exercise.all, :id, :name, class: 'form-control' %>
            <%= f.submit "Add", class:"btn-primary" %>
        </div>
    <% end %>
    </div>
<% end %>

<hr />

<h4>Exercises in this workout: </h4>
    <ol class="list-group">
        <% @workout.workout_exercises.each do |workout_exercise|%>
        <li class="list-group-item"><%= link_to workout_exercise.exercise.name, exercise_path(workout_exercise.exercise) %>
        | <b><%= workout_exercise.exercise.category.name %></b>
        | <b>Difficulty Level: </b><%= workout_exercise.exercise.difficulty %>
        | <b>Muscle Group: </b><%= workout_exercise.exercise.muscle_group %>
        | <%= link_to "Video Link", workout_exercise.exercise.video_link %><br />
        
        <b>Instructions: </b><%= workout_exercise.exercise.instructions %>
        <% if logged_in_as_coach? && current_user.id == @workout.client.coach.id %>
            <%= button_to "Remove this exercise", delete_workout_exercise_path(workout_exercise), method: 'delete', class: "btn-primary", data: { confirm: "Are you sure you want to delete '#{ workout_exercise.exercise.name }' from '#{ @workout.name }'?" } %>
        <% end %>
        <br />
        </li>
        <% end %>
    </ol>