config/routes.rb
Rails.application.routes.draw do

  root 'static#home', as: 'home'

  ##Session
  get '/client_login', to: 'sessions#client_login', as: 'client_login'
  post '/client_login', to: 'sessions#login_client'
  get '/coach_login', to: 'sessions#coach_login', as: 'coach_login'
  post '/coach_login', to: 'sessions#login_coach'
  delete '/', to: 'sessions#logout', as: 'logout'

  ##Expertise
  post '/expertises', to: 'expertises#create', as: 'new_expertise'
  delete '/expertises/:id', to: 'expertises#destroy', as: 'delete_expertise'

  ##WorkoutExercise
  post '/workout_exercises', to: 'workout_exercises#create', as: 'new_workout_exercise'
  delete '/workout_exercises/:id', to: 'workout_exercises#destroy', as: 'delete_workout_exercise'

  ##Workouts
  get '/workouts', to: 'workouts#index', as: 'workouts'
  get '/workouts/new', to: 'workouts#new', as: 'new_workout'
  post '/workouts', to: 'workouts#create'
  patch '/workouts/:id/completed', to: 'workouts#completed', as: 'completed_workout' 
  get '/workouts/:id', to: 'workouts#show', as: 'workout'
  delete '/workouts/:id', to: 'workouts#destroy', as: 'delete_workout'

  ##Exercise
  get '/exercises', to: 'exercises#index', as: 'exercises'
  get '/exercises/new', to: 'exercises#new', as: 'new_exercise'
  post '/exercises', to: 'exercises#create'
  get '/exercises/:id/edit', to: 'exercises#edit', as: 'edit_exercise'
  patch '/exercises/:id', to: 'exercises#update'
  get '/exercises/:id', to: 'exercises#show', as: 'exercise'

  ##Category
  get '/categories/:id/edit', to: 'categories#edit', as: 'edit_category'
  patch '/categories/:id', to: 'categories#update'
  get '/categories', to: 'categories#index', as: 'categories'
  get '/categories/:id', to: 'categories#show', as:'category'

  ##Coaches
  get '/coaches', to: 'coaches#index', as: 'coaches'
  get '/coaches/new', to: 'coaches#new', as: 'new_coach'
  post '/coaches', to: 'coaches#create'
  get '/coaches/:id/edit', to: 'coaches#edit', as: 'edit_coach'
  patch '/coaches/:id', to: 'coaches#update'
  get '/coaches/:id', to: 'coaches#show', as: 'coach'

  ##Clients
  get '/clients', to: 'clients#index', as: 'clients'
  get '/clients/new', to: 'clients#new', as: 'new_client'
  post '/clients', to: 'clients#create'
  get '/clients/:id/edit', to: 'clients#edit', as: 'edit_client'
  patch '/clients/:id', to: 'clients#update'
  get '/clients/:id', to: 'clients#show', as: 'client'
  
end

app/models/client.rb
class Client < ApplicationRecord
    has_secure_password
    belongs_to :coach
    has_many :workouts

    validates :name, presence: true, uniqueness: true
    validates_presence_of :birthday

    def age
        Date.today.year - self.birthday.year
    end

    def level_up
        self.experience += 1
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  
  skip_before_action :authorize, only: [:new, :create]

  def index
    @all_clients = Client.all
  end

  def show
  end

  def new
    @new_client = Client.new
  end

  def create
    newly_created_client = Client.create( client_params )
    if newly_created_client.valid?
      flash[ :messages ] = [ "Account for client #{ newly_created_client.name } created! Please log in!" ]
      redirect_to client_login_path
    else
      flash[ :messages ] = newly_created_client.errors.full_messages
      redirect_to new_client_path
    end
  end

  def edit
  end

  def update
    if @client.update( client_params )
      redirect_to client_path( @client )
    else
      flash[ :messages ] = @client.errors.full_messages
      redirect_to edit_client_path
    end
  end

  def destroy
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require( :client ).permit( :coach_id, :name, :password, :password_confirmation, :birthday, :avatar, :bio )
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<h1>
    <%= image_tag "ClientIcon.svg", class: "model-icon" %>
    Edit <%= @client.name %>'s profile
</h1>
<% if flash[ :messages ] %>
    <ul>
    <% flash[ :messages ].each do | error_message | %>
        <li style="color:red;"><%= error_message %></li>
    <% end %>
    </ul>
<% end %>

<div class="input-group">
    <%= form_for @client do | f | %>
        <div class="input-group-prepend">
            <%= f.label :name, "Update your username:", class: 'input-group-text' %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :password, "Update your password:", class: 'input-group-text' %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :password_confirmation, "Confirm your password:", class: 'input-group-text' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :coach_id, "Select your coach:", class: 'input-group-text' %>
            <%= f.collection_select :coach_id, Coach.all, :id, :name, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :birthday, "Select your birthday:", class: 'input-group-text' %>
            <%= date_select :client, :birthday, start_year: Date.current.year, end_year: 1920, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :avatar, "Avatar URL", class: 'input-group-text' %>
            <%= f.text_field :avatar, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :bio, class: 'input-group-text' %><br />
            <%= f.text_area :bio, class: 'form-control' %>
        </div>
        <%= f.submit "Update WorkItOuter profile", class: 'btn-primary' %>
    <% end %>
</div>

app/views/clients/index.html.erb
<h1>
    <%= image_tag "ClientIcon.svg", class: "model-icon" %>
    All WorkItOuters
</h1>

<div class="cards">
    <% @all_clients.each do |client|%>
       <div class="card">
            <%= image_tag client.avatar, class: "card-img-top" %>
            <div class="card-body">
                <h2 class="card-title"><%= client.name %></h2>
                <p class="card-text"><%= client.bio %></p>
                <%= button_to "View Profile", client_path(client), method: "get", class: "btn-primary" %>
            </div>
        </div>
    <% end %>
</div>

app/views/clients/new.html.erb
<h1>
    <%= image_tag "ClientIcon.svg", class: "model-icon" %>
    Create a new client
</h1>

<% if flash[ :messages ] %>
    <ul>
    <% flash[ :messages ].each do | error_message | %>
        <li style="color:red;"><%= error_message %></li>
    <% end %>
    </ul>
<% end %>

<div class="input-group">
    <%= form_for @new_client do | f | %>
        <div class="input-group-prepend">
            <%= f.label :name, "Enter your username:", class: 'input-group-text' %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :password, "Enter your password:", class: 'input-group-text' %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :password_confirmation, "Confirm your password:", class: 'input-group-text' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :coach_id, "Select your coach:", class: 'input-group-text' %>
            <%= f.collection_select :coach_id, Coach.all, :id, :name, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :birthday, "Select your birthday:", class: 'input-group-text' %>
            <%= date_select :client, :birthday, start_year: Date.current.year, end_year: 1920, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :avatar, "Avatar URL", class: 'input-group-text' %>
            <%= f.text_field :avatar, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :bio, class: 'input-group-text' %><br />
            <%= f.text_area :bio, class: 'form-control' %>
        </div>
        <%= f.submit "Become a WorkItOuter!", class: 'btn-primary' %>
    <% end %>
</div>

app/views/clients/show.html.erb
<h1>
    <%= image_tag "ClientIcon.svg", class: "model-icon" %>
    Client Profile: <%= @client.name %>
</h1>

<% if flash[ :messages ] %>
    <ul>
    <% flash[ :messages ].each do | error_message | %>
        <li style="color:red;"><%= error_message %></li>
    <% end %>
    </ul>
<% end %>

<table class="table table-borderless"><tr>
    <td id="avatar"><%= image_tag @client.avatar, size: "100" %></td>
    <td>
        <p><%= @client.bio %></p>
        <p>Age: <%= @client.age %></p>
        <p>Level: <%= @client.experience %></p>
        <p>Started working out on: <%= @client.created_at.strftime("%F") %></p>
        <p>My coach: <%= link_to @client.coach.name, coach_path(@client.coach) %></p>
    </td>
</tr></table>

<% if logged_in_as_client? && current_user.id == @client.id %>
    <%= button_to "Update Profile", edit_client_path(@client), method: 'get', class: "btn-primary"  %>
<% end %>

<hr />

<h4> Current workouts</h4>

<div class="cards">
    <% @client.workouts.each do |workout|%>
       <div class="card">
            <div class="card-body">
                <h2 class="card-title"><%= workout.name %></h2>
                <p class="card-text"><%= workout.length %> min. | <%= workout.completed ? "Completed on: #{workout.updated_at}" : "Not Completed"%></p>
                <%= button_to "View Details", workout_path(workout), method: "get", class: "btn-primary" %>
                <% if (logged_in_as_client? && current_user.id == @client.id) || (logged_in_as_coach? && current_user.id == @client.coach.id) %>
                    <%= button_to "Delete this workout", delete_workout_path(workout), method: "delete", data: {confirm: "Are you sure?"}, class: "btn-primary" %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>


<% if logged_in_as_coach? && current_user.id == @client.coach.id %>
    <%= button_to "Add a workout", new_workout_path, method: "get", class: "btn-primary"  %>
<% end %>

<p>&nbsp;</p>