config/routes.rb
Rails.application.routes.draw do

  root 'static#home', as: 'home'

  ##Session
  get '/client_login', to: 'sessions#client_login', as: 'client_login'
  post '/client_login', to: 'sessions#login_client'
  get '/coach_login', to: 'sessions#coach_login', as: 'coach_login'
  post '/coach_login', to: 'sessions#login_coach'
  delete '/', to: 'sessions#logout', as: 'logout'

  ##Expertise
  post '/expertises', to: 'expertises#create', as: 'new_expertise'
  delete '/expertises/:id', to: 'expertises#destroy', as: 'delete_expertise'

  ##WorkoutExercise
  post '/workout_exercises', to: 'workout_exercises#create', as: 'new_workout_exercise'
  delete '/workout_exercises/:id', to: 'workout_exercises#destroy', as: 'delete_workout_exercise'

  ##Workouts
  get '/workouts', to: 'workouts#index', as: 'workouts'
  get '/workouts/new', to: 'workouts#new', as: 'new_workout'
  post '/workouts', to: 'workouts#create'
  patch '/workouts/:id/completed', to: 'workouts#completed', as: 'completed_workout' 
  get '/workouts/:id', to: 'workouts#show', as: 'workout'
  delete '/workouts/:id', to: 'workouts#destroy', as: 'delete_workout'

  ##Exercise
  get '/exercises', to: 'exercises#index', as: 'exercises'
  get '/exercises/new', to: 'exercises#new', as: 'new_exercise'
  post '/exercises', to: 'exercises#create'
  get '/exercises/:id/edit', to: 'exercises#edit', as: 'edit_exercise'
  patch '/exercises/:id', to: 'exercises#update'
  get '/exercises/:id', to: 'exercises#show', as: 'exercise'

  ##Category
  get '/categories/:id/edit', to: 'categories#edit', as: 'edit_category'
  patch '/categories/:id', to: 'categories#update'
  get '/categories', to: 'categories#index', as: 'categories'
  get '/categories/:id', to: 'categories#show', as:'category'

  ##Coaches
  get '/coaches', to: 'coaches#index', as: 'coaches'
  get '/coaches/new', to: 'coaches#new', as: 'new_coach'
  post '/coaches', to: 'coaches#create'
  get '/coaches/:id/edit', to: 'coaches#edit', as: 'edit_coach'
  patch '/coaches/:id', to: 'coaches#update'
  get '/coaches/:id', to: 'coaches#show', as: 'coach'

  ##Clients
  get '/clients', to: 'clients#index', as: 'clients'
  get '/clients/new', to: 'clients#new', as: 'new_client'
  post '/clients', to: 'clients#create'
  get '/clients/:id/edit', to: 'clients#edit', as: 'edit_client'
  patch '/clients/:id', to: 'clients#update'
  get '/clients/:id', to: 'clients#show', as: 'client'
  
end

app/models/coach.rb
class Coach < ApplicationRecord
    has_secure_password
    has_many :clients
    has_many :expertises
    has_many :categories, through: :expertises

    validates :name, presence: true, uniqueness: true

end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]

  skip_before_action :authorize, only: [ :new, :create ]
  
  def index
    @coaches = Coach.all
  end

  def show
    @expertise = Expertise.new
    @expertise.build_category
  end

  def new
    @new_coach = Coach.new
  end

  def create
    newly_created_coach = Coach.create( coach_params )
    if newly_created_coach.valid?
      flash[ :messages ] = [ "Account for coach #{ newly_created_coach.name } created! Please log in!" ]
      redirect_to coach_login_path
    else
      flash[ :messages ] = newly_created_coach.errors.full_messages
      redirect_to new_coach_path
    end
  end

  def edit
  end

  def update
    if @coach.update( coach_params )
      redirect_to coach_path( @coach )
    else
      flash[ :messages ] = @coach.errors.full_messages
      redirect_to edit_coach_path
    end
  end

  def destroy
  end

  private

  def set_coach
    @coach = Coach.find(params[:id])
  end

  def coach_params
    params.require( :coach ).permit( :name, :password, :password_confirmation, :avatar, :bio )
  end

end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/edit.html.erb
<h1>
    <%= image_tag "CoachIcon.svg", class: "model-icon" %>
    Edit coach <%= @coach.name %>'s profile
</h1>

<% if flash[ :messages ] %>
    <ul>
    <% flash[ :messages ].each do | error_message | %>
        <li style="color:red;"><%= error_message %></li>
    <% end %>
    </ul>
<% end %>

<div class="input-group">
    <%= form_for @coach do | f | %>
        <div class="input-group-prepend">
            <%= f.label :name, "Update your username:", class: 'input-group-text' %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :password, "Update your password:", class: 'input-group-text' %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :password_confirmation, "Confirm your password:", class: 'input-group-text' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :avatar, "Avatar URL:", class: 'input-group-text' %>
            <%= f.text_field :avatar, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :bio, "Bio:", class: 'input-group-text' %><br />
            <%= f.text_area :bio, class: 'form-control' %>
        </div>
        <%= f.submit "Update coach profile", class: 'btn-primary' %>
    <% end %>
</div>

app/views/coaches/index.html.erb
<h1>
    <%= image_tag "CoachIcon.svg", class: "model-icon" %>
    All Coaches
</h1>

<div class="cards">
    <% @coaches.each do |coach|%>
       <div class="card">
            <%= image_tag coach.avatar, class: "card-img-top" %>
            <div class="card-body">
                <h2 class="card-title"><%= coach.name %></h2>
                <p class="card-text"><%= coach.bio %></p>
                <%= button_to "View Profile", coach_path(coach), method: "get", class: "btn-primary" %>
            </div>
        </div>
    <% end %>
</div>

app/views/coaches/new.html.erb
<h1>
    <%= image_tag "CoachIcon.svg", class: "model-icon" %>
    Create a new coach
</h1>

<% if flash[ :messages ] %>
    <ul>
    <% flash[ :messages ].each do | error_message | %>
        <li style="color:red;"><%= error_message %></li>
    <% end %>
    </ul>
<% end %>

<div class="input-group">
    <%= form_for @new_coach do | f | %>
        <div class="input-group-prepend">
            <%= f.label :name, "Enter your username:", class: 'input-group-text' %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :password, "Enter your password:", class: 'input-group-text' %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :password_confirmation, "Confirm your password:", class: 'input-group-text' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :avatar, "Avatar URL:", class: 'input-group-text' %>
            <%= f.text_field :avatar, class: 'form-control' %>
        </div>
        <div class="input-group-prepend">
            <%= f.label :bio, "Bio:", class: 'input-group-text' %><br />
            <%= f.text_area :bio, class: 'form-control' %>
        </div>
        <%= f.submit "Become a coach!", class: 'btn-primary' %>
    <% end %>
</div>

app/views/coaches/show.html.erb
<h1>
    <%= image_tag "CoachIcon.svg", class: "model-icon" %>
    Coach Profile: <%= @coach.name%>
</h1>

<% if flash[ :messages ] %>
    <ul>
    <% flash[ :messages ].each do | error_message | %>
        <li style="color:red;"><%= error_message %></li>
    <% end %>
    </ul>
<% end %>

<table class="table table-borderless"><tr>
    <td id="avatar"><%= image_tag @coach.avatar, size: "100" %></td>
    <td>
        <p><%= @coach.bio %></p>
        <p>Started coaching on: <%= @coach.created_at.strftime("%F") %></p>
        <p>My clients:</p>
        <ol>
            <% @coach.clients.each do |client| %>
                <li><%= link_to client.name, client_path(client) %></li>
            <% end %>
        </ol>
    </td>
</tr></table>

<% if logged_in_as_coach? && current_user.id == @coach.id %>
    <div class="btn-group">
        <%= button_to "Update Profile", edit_coach_path(@coach), method: 'get', class: "btn-primary" %>
        <%= button_to "Add a workout", new_workout_path, method: "get", class: "btn-primary" %>
    </div>
<% end %>

<hr />

<h2>Specialties</h2>
<div class="cards">
    <% @coach.expertises.each do | expertise |%>
       <div class="card">
            <div class="card-body">
                <h4 class="card-title"><%= expertise.category.name %></h4>
                <p class="card-text">Mobility: <%= expertise.category.mobility %></p>
                <%= button_to "View Exercises/Coaches", category_path(expertise.category), method: "get", class: "btn-primary" %>
                <% if logged_in_as_coach? && current_user.id == @coach.id %>
                    <%= button_to "Remove this category", delete_expertise_path(expertise), method: 'delete', class: "btn-primary", data: { confirm: "Are you sure?" } %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<% if logged_in_as_coach? && current_user.id == @coach.id %>
    <div class="input-group">
        <%= form_with scope: :expertise, url: new_expertise_path(params: {coach_id: @coach.id}), method: 'post' do |f| %>
            <div class="input-group-prepend">
                <%= f.label "Add to specialties", class: 'input-group-text' %>
                <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select a category", class: 'form-control' %>
                <span class="input-group-text">Or create a new one!</span>
                <%= f.fields_for :category, Category.new do | category_attributes | %>
                    <%= category_attributes.label :name, "Name:", class: 'input-group-text'  %>
                    <%= category_attributes.text_field :name, class: 'form-control' %>
                    <%= category_attributes.label :mobility, "Mobility level:", class: 'input-group-text'  %>
                    <%= category_attributes.text_field :mobility, class: 'form-control'  %>
                <% end %>
                <%= f.submit "Add expertise", class: "btn-primary"%>
            </div>
        <% end %>
    </div>
<% end %>

<p>&nbsp;</p>