config/routes.rb
Rails.application.routes.draw do

  root 'static#home', as: 'home'

  ##Session
  get '/client_login', to: 'sessions#client_login', as: 'client_login'
  post '/client_login', to: 'sessions#login_client'
  get '/coach_login', to: 'sessions#coach_login', as: 'coach_login'
  post '/coach_login', to: 'sessions#login_coach'
  delete '/', to: 'sessions#logout', as: 'logout'

  ##Expertise
  post '/expertises', to: 'expertises#create', as: 'new_expertise'
  delete '/expertises/:id', to: 'expertises#destroy', as: 'delete_expertise'

  ##WorkoutExercise
  post '/workout_exercises', to: 'workout_exercises#create', as: 'new_workout_exercise'
  delete '/workout_exercises/:id', to: 'workout_exercises#destroy', as: 'delete_workout_exercise'

  ##Workouts
  get '/workouts', to: 'workouts#index', as: 'workouts'
  get '/workouts/new', to: 'workouts#new', as: 'new_workout'
  post '/workouts', to: 'workouts#create'
  patch '/workouts/:id/completed', to: 'workouts#completed', as: 'completed_workout' 
  get '/workouts/:id', to: 'workouts#show', as: 'workout'
  delete '/workouts/:id', to: 'workouts#destroy', as: 'delete_workout'

  ##Exercise
  get '/exercises', to: 'exercises#index', as: 'exercises'
  get '/exercises/new', to: 'exercises#new', as: 'new_exercise'
  post '/exercises', to: 'exercises#create'
  get '/exercises/:id/edit', to: 'exercises#edit', as: 'edit_exercise'
  patch '/exercises/:id', to: 'exercises#update'
  get '/exercises/:id', to: 'exercises#show', as: 'exercise'

  ##Category
  get '/categories/:id/edit', to: 'categories#edit', as: 'edit_category'
  patch '/categories/:id', to: 'categories#update'
  get '/categories', to: 'categories#index', as: 'categories'
  get '/categories/:id', to: 'categories#show', as:'category'

  ##Coaches
  get '/coaches', to: 'coaches#index', as: 'coaches'
  get '/coaches/new', to: 'coaches#new', as: 'new_coach'
  post '/coaches', to: 'coaches#create'
  get '/coaches/:id/edit', to: 'coaches#edit', as: 'edit_coach'
  patch '/coaches/:id', to: 'coaches#update'
  get '/coaches/:id', to: 'coaches#show', as: 'coach'

  ##Clients
  get '/clients', to: 'clients#index', as: 'clients'
  get '/clients/new', to: 'clients#new', as: 'new_client'
  post '/clients', to: 'clients#create'
  get '/clients/:id/edit', to: 'clients#edit', as: 'edit_client'
  patch '/clients/:id', to: 'clients#update'
  get '/clients/:id', to: 'clients#show', as: 'client'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :exercises
    has_many :expertises
    has_many :coaches, through: :expertises

    validates :mobility, inclusion: { in: %w( low medium high ), message: "must be low, medium, or high" }
    validates :name, presence: true, uniqueness: true
end

app/models/client.rb
class Client < ApplicationRecord
    has_secure_password
    belongs_to :coach
    has_many :workouts

    validates :name, presence: true, uniqueness: true
    validates_presence_of :birthday

    def age
        Date.today.year - self.birthday.year
    end

    def level_up
        self.experience += 1
    end
end

app/models/coach.rb
class Coach < ApplicationRecord
    has_secure_password
    has_many :clients
    has_many :expertises
    has_many :categories, through: :expertises

    validates :name, presence: true, uniqueness: true

end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :category
  accepts_nested_attributes_for :category

  has_many :workout_exercises
  has_many :workouts, through: :workout_exercises

  def embed_video
    "<iframe width=\"640\" height=\"360\" src=\"https://www.youtube.com/embed/#{ self.url }\"></iframe>"
  end

  def video_link
    "http://youtu.be/#{ self.url }"
  end

end

app/models/expertise.rb
class Expertise < ApplicationRecord
  belongs_to :coach
  belongs_to :category

  accepts_nested_attributes_for :category

  validates_uniqueness_of :category, scope: :coach
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :client

  has_many :workout_exercises
  has_many :exercises, through: :workout_exercises

  validates :name, presence: true
  validates :length, numericality: { greater_than: 0 }
end

app/models/workout_exercise.rb
class WorkoutExercise < ApplicationRecord
  belongs_to :workout
  belongs_to :exercise
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  
  skip_before_action :authorize, only: [:new, :create]

  def index
    @all_clients = Client.all
  end

  def show
  end

  def new
    @new_client = Client.new
  end

  def create
    newly_created_client = Client.create( client_params )
    if newly_created_client.valid?
      flash[ :messages ] = [ "Account for client #{ newly_created_client.name } created! Please log in!" ]
      redirect_to client_login_path
    else
      flash[ :messages ] = newly_created_client.errors.full_messages
      redirect_to new_client_path
    end
  end

  def edit
  end

  def update
    if @client.update( client_params )
      redirect_to client_path( @client )
    else
      flash[ :messages ] = @client.errors.full_messages
      redirect_to edit_client_path
    end
  end

  def destroy
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require( :client ).permit( :coach_id, :name, :password, :password_confirmation, :birthday, :avatar, :bio )
  end

end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]

  skip_before_action :authorize, only: [ :new, :create ]
  
  def index
    @coaches = Coach.all
  end

  def show
    @expertise = Expertise.new
    @expertise.build_category
  end

  def new
    @new_coach = Coach.new
  end

  def create
    newly_created_coach = Coach.create( coach_params )
    if newly_created_coach.valid?
      flash[ :messages ] = [ "Account for coach #{ newly_created_coach.name } created! Please log in!" ]
      redirect_to coach_login_path
    else
      flash[ :messages ] = newly_created_coach.errors.full_messages
      redirect_to new_coach_path
    end
  end

  def edit
  end

  def update
    if @coach.update( coach_params )
      redirect_to coach_path( @coach )
    else
      flash[ :messages ] = @coach.errors.full_messages
      redirect_to edit_coach_path
    end
  end

  def destroy
  end

  private

  def set_coach
    @coach = Coach.find(params[:id])
  end

  def coach_params
    params.require( :coach ).permit( :name, :password, :password_confirmation, :avatar, :bio )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize, only: [:client_login, :login_client, :coach_login, :login_coach, :logout]
  
  
  def client_login
  end

  def login_client
    @client = Client.find_by( name: params[ :name ] )
    if @client && @client.authenticate( params[ :password ] )
      session[ :id ], session[ :coach? ] = @client.id, false
      redirect_to client_path( @client )
    else
      flash[ :messages ] = [ "Invalid username or password!" ]
      redirect_to client_login_path
    end
  end

  def coach_login
  end

  def login_coach
    @coach = Coach.find_by( name: params[ :name ] )
    if @coach && @coach.authenticate( params[ :password ] )
      session[ :id ], session[ :coach? ] = @coach.id, true
      redirect_to coach_path( @coach )
    else
      flash[ :messages ] = [ "Invalid username or password!" ]
      redirect_to coach_login_path
    end
  end

  def logout
    session[ :id ], session[ :coach? ] = nil, nil
    redirect_to home_path
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_action :authorize, only: [:home]
  
  def home
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/expertises_helper.rb
module ExpertisesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_menu.html.erb
<% if logged_in? %>
    <div class="btn-group-vertical">
        <%= button_to "Browse categories", categories_path, method: "get", class: 'btn' %>
        <%= button_to "Browse exercises", exercises_path, method: "get", class: 'btn' %>
        <%= button_to "Browse WorkItOuters", clients_path, method: "get", class: 'btn' %>
        <%= button_to "Browse coaches", coaches_path, method: "get", class: 'btn' %>
    </div>
<% else %>
    <div class="btn-group-vertical">
        <%= label_tag "Log in:" %>
        <%= button_to "As a Client", client_login_path, method: "get", class: "btn" %>
        <%= button_to "As a Coach", coach_login_path, method: "get", class: "btn" %>
        <hr />
        <%= label_tag "Not a user? Sign up:" %>
        <%= button_to "As a Client", new_client_path, method: "get", class: "btn" %>
        <%= button_to "As a Coach", new_coach_path, method: "get", class: "btn" %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<% if logged_in? %>
  <%== "<a href=\"#{ logged_in_as_coach? ? coach_path( current_user ) : client_path( current_user ) }\">" %>
<% else %>
  <%== "<a href=\"#{ home_path }\">" %>
<% end %>
  <%= image_tag "WorkItOutLogo.svg", class: "logo" %>
</a>

<div id="status">
  <%= logged_in? ? "Logged in as #{ logged_in_as_coach? ? "Coach" : "" } #{ current_user.name }" : "Logged out" %>
  <%= " | " if logged_in? %>
  <%= link_to "My profile", logged_in_as_coach? ? coach_path( current_user ) : client_path( current_user ) if logged_in? %>
  <%= " | " if logged_in? %>
  <%= link_to "Log out", logout_path, method: "delete", data: { confirm: "Are you sure?" } if logged_in? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkItOut</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="navbar" id="navbar">
      <%= render "layouts/navbar" %>
    </div>
    <div class="grid row" id="content">
      <div class="col" id="menu">
        <%= render "layouts/menu" %>
      </div>
      <div class="col" id="display">
        <%= yield %>
      </div>
    </div>
  </body>
</html>